/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClassLevel = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'classLevel' : ClassLevel,
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ParentContact = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const StudentProfile = IDL.Record({
  'contact' : ContactInfo,
  'parentContact' : ParentContact,
  'name' : IDL.Text,
  'classLevel' : ClassLevel,
  'enrolledCourses' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'present' : IDL.Bool,
  'date' : Time,
  'courseId' : IDL.Text,
});
export const TestScore = IDL.Record({
  'maxScore' : IDL.Nat,
  'date' : Time,
  'score' : IDL.Nat,
  'courseId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ClassLevel], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'editCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ClassLevel], [], []),
  'enrollInCourse' : IDL.Func([IDL.Text], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getCallerAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getCallerStudentProfile' : IDL.Func(
      [],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getCallerTestScores' : IDL.Func([], [IDL.Vec(TestScore)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoursesForClass' : IDL.Func([ClassLevel], [IDL.Vec(Course)], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [IDL.Record({ 'totalStudents' : IDL.Nat, 'totalCourses' : IDL.Nat })],
      ['query'],
    ),
  'getStudentAttendance' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'getStudentTestScores' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TestScore)],
      ['query'],
    ),
  'getStudentsByClass' : IDL.Func(
      [ClassLevel],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
  'recordTestScore' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'registerStudent' : IDL.Func(
      [
        IDL.Text,
        ClassLevel,
        ContactInfo,
        ParentContact,
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudentsByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentProfile)],
      ['query'],
    ),
  'updateCallerStudentProfile' : IDL.Func(
      [
        IDL.Text,
        ClassLevel,
        ContactInfo,
        ParentContact,
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [],
      [],
    ),
  'updateStudentProfile' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        ClassLevel,
        ContactInfo,
        ParentContact,
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClassLevel = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'classLevel' : ClassLevel,
  });
  const ContactInfo = IDL.Record({ 'email' : IDL.Text, 'phone' : IDL.Text });
  const ParentContact = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const StudentProfile = IDL.Record({
    'contact' : ContactInfo,
    'parentContact' : ParentContact,
    'name' : IDL.Text,
    'classLevel' : ClassLevel,
    'enrolledCourses' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'present' : IDL.Bool,
    'date' : Time,
    'courseId' : IDL.Text,
  });
  const TestScore = IDL.Record({
    'maxScore' : IDL.Nat,
    'date' : Time,
    'score' : IDL.Nat,
    'courseId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ClassLevel], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'editCourse' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, ClassLevel], [], []),
    'enrollInCourse' : IDL.Func([IDL.Text], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getCallerAttendance' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerStudentProfile' : IDL.Func(
        [],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getCallerTestScores' : IDL.Func([], [IDL.Vec(TestScore)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoursesForClass' : IDL.Func([ClassLevel], [IDL.Vec(Course)], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [IDL.Record({ 'totalStudents' : IDL.Nat, 'totalCourses' : IDL.Nat })],
        ['query'],
      ),
    'getStudentAttendance' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'getStudentTestScores' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TestScore)],
        ['query'],
      ),
    'getStudentsByClass' : IDL.Func(
        [ClassLevel],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([IDL.Principal, IDL.Text, IDL.Bool], [], []),
    'recordTestScore' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'registerStudent' : IDL.Func(
        [
          IDL.Text,
          ClassLevel,
          ContactInfo,
          ParentContact,
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudentsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'updateCallerStudentProfile' : IDL.Func(
        [
          IDL.Text,
          ClassLevel,
          ContactInfo,
          ParentContact,
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [],
        [],
      ),
    'updateStudentProfile' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          ClassLevel,
          ContactInfo,
          ParentContact,
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };