/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'present' : boolean,
  'date' : Time,
  'courseId' : string,
}
export type ClassLevel = bigint;
export interface ContactInfo { 'email' : string, 'phone' : string }
export interface Course {
  'id' : string,
  'name' : string,
  'description' : string,
  'classLevel' : ClassLevel,
}
export type ExternalBlob = Uint8Array;
export interface ParentContact { 'name' : string, 'phone' : string }
export interface StudentProfile {
  'contact' : ContactInfo,
  'parentContact' : ParentContact,
  'name' : string,
  'classLevel' : ClassLevel,
  'enrolledCourses' : Array<string>,
}
export interface StudyMaterial {
  'id' : string,
  'title' : string,
  'file' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'classLevel' : ClassLevel,
  'courseId' : string,
  'uploadTime' : Time,
  'uploadedBy' : Principal,
}
export interface TestScore {
  'maxScore' : bigint,
  'date' : Time,
  'score' : bigint,
  'courseId' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'addCourse' : ActorMethod<[string, string, string, ClassLevel], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStudyMaterial' : ActorMethod<[string], undefined>,
  'downloadStudyMaterial' : ActorMethod<[string], StudyMaterial>,
  'editCourse' : ActorMethod<[string, string, string, ClassLevel], undefined>,
  'enrollInCourse' : ActorMethod<[string], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllStudents' : ActorMethod<[], Array<StudentProfile>>,
  'getAllStudyMaterials' : ActorMethod<
    [[] | [string], [] | [ClassLevel]],
    Array<StudyMaterial>
  >,
  'getCallerAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getCallerStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerTestScores' : ActorMethod<[], Array<TestScore>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoursesForClass' : ActorMethod<[ClassLevel], Array<Course>>,
  'getDashboardStats' : ActorMethod<
    [],
    { 'totalStudents' : bigint, 'totalCourses' : bigint }
  >,
  'getStudentAttendance' : ActorMethod<[Principal], Array<AttendanceRecord>>,
  'getStudentProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'getStudentTestScores' : ActorMethod<[Principal], Array<TestScore>>,
  'getStudentsByClass' : ActorMethod<[ClassLevel], Array<StudentProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[Principal, string, boolean], undefined>,
  'recordTestScore' : ActorMethod<
    [Principal, string, bigint, bigint],
    undefined
  >,
  'registerStudent' : ActorMethod<
    [string, ClassLevel, ContactInfo, ParentContact, [] | [Array<string>]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStudentsByName' : ActorMethod<[string], Array<StudentProfile>>,
  'updateCallerStudentProfile' : ActorMethod<
    [string, ClassLevel, ContactInfo, ParentContact, [] | [Array<string>]],
    undefined
  >,
  'updateStudentProfile' : ActorMethod<
    [
      Principal,
      string,
      ClassLevel,
      ContactInfo,
      ParentContact,
      [] | [Array<string>],
    ],
    undefined
  >,
  'updateStudyMaterial' : ActorMethod<
    [string, string, string, string, string, ClassLevel],
    undefined
  >,
  'uploadStudyMaterial' : ActorMethod<
    [string, string, string, string, ExternalBlob, string, ClassLevel],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];